package com.jstamps.docai.enums;

public enum Symptoms {

    SYM_1("Abdomen acute"),
    SYM_2("Abdominal bloating"),
    SYM_3("Abdominal tenderness"),
    SYM_4("Abnormal sensation"),
    SYM_5("Abnormally hard consistency"),
    SYM_6("Abscess bacterial"),
    SYM_7("Absences finding"),
    SYM_8("Achalasia"),
    SYM_9("Ache"),
    SYM_10("Adverse effect"),
    SYM_11("Adverse reaction"),
    SYM_12("Agitation"),
    SYM_13("Air fluid level"),
    SYM_14("Alcohol binge episode"),
    SYM_15("Alcoholic withdrawal symptoms"),
    SYM_16("Ambidexterity"),
    SYM_17("Angina Pectoris"),
    SYM_18("Anorexia"),
    SYM_19("Anosmia"),
    SYM_20("Aphagia"),
    SYM_21("Apyrexial"),
    SYM_22("Arthralgia"),
    SYM_23("Ascites"),
    SYM_24("Asterixis"),
    SYM_25("Asthenia"),
    SYM_26("Asymptomatic"),
    SYM_27("Ataxia"),
    SYM_28("Atypia"),
    SYM_29("Aura"),
    SYM_30("Awakening early"),
    SYM_31("Barking cough"),
    SYM_32("Bedridden"),
    SYM_33("Behavior hyperactive"),
    SYM_34("Behavior showing increased motor activity"),
    SYM_35("Blackout"),
    SYM_36("Blanch"),
    SYM_37("Bleeding of vagina"),
    SYM_38("Bowel sounds decreased"),
    SYM_39("Bradycardia"),
    SYM_40("Bradykinesia"),
    SYM_41("Breakthrough pain"),
    SYM_42("Breath sounds decreased"),
    SYM_43("Breath-holding spell"),
    SYM_44("Breech presentation"),
    SYM_45("Bruit"),
    SYM_46("Burning sensation"),
    SYM_47("Cachexia"),
    SYM_48("Cardiomegaly"),
    SYM_49("Cardiovascular event"),
    SYM_50("Cardiovascular finding"),
    SYM_51("Catatonia"),
    SYM_52("Catching breath"),
    SYM_53("Charleyhorse"),
    SYM_54("Chest discomfort"),
    SYM_55("Chest tightness"),
    SYM_56("Chill"),
    SYM_57("Choke"),
    SYM_58("Cicatrisation"),
    SYM_59("Clammy skin"),
    SYM_60("Claudication"),
    SYM_61("Clonus"),
    SYM_62("Clumsiness"),
    SYM_63("Colic abdominal"),
    SYM_64("Consciousness clear"),
    SYM_65("Constipation"),
    SYM_66("Coordination abnormal"),
    SYM_67("Cough"),
    SYM_68("Cushingoid facies"),
    SYM_69("Cushingoid Habitus"),
    SYM_70("Cyanosis"),
    SYM_71("Cystic lesion"),
    SYM_72("Debilitation"),
    SYM_73("Decompensation"),
    SYM_74("Decreased body weight"),
    SYM_75("Decreased stool caliber"),
    SYM_76("Decreased translucency"),
    SYM_77("Diarrhea"),
    SYM_78("Difficulty"),
    SYM_79("Difficulty passing urine"),
    SYM_80("Disequilibrium"),
    SYM_81("Distended abdomen"),
    SYM_82("Distress respiratory"),
    SYM_83("Disturbed family"),
    SYM_84("Dizziness"),
    SYM_85("Dizzy spells"),
    SYM_86("Drool"),
    SYM_87("Drowsiness"),
    SYM_88("Dry cough"),
    SYM_89("Dullness"),
    SYM_90("Dysarthria"),
    SYM_91("Dysdiadochokinesia"),
    SYM_92("Dysesthesia"),
    SYM_93("Dyspareunia"),
    SYM_94("Dyspnea"),
    SYM_95("Dyspnea on exertion"),
    SYM_96("Dysuria"),
    SYM_97("Ecchymosis"),
    SYM_98("Egophony"),
    SYM_99("Elation"),
    SYM_100("Emphysematous change"),
    SYM_101("Energy increased"),
    SYM_102("Enuresis"),
    SYM_103("Erythema"),
    SYM_104("Estrogen use"),
    SYM_105("Excruciating pain"),
    SYM_106("Exhaustion"),
    SYM_107("Extrapyramidal sign"),
    SYM_108("Extreme exhaustion"),
    SYM_109("Facial paresis"),
    SYM_110("Fall"),
    SYM_111("Fatigability"),
    SYM_112("Fatigue"),
    SYM_113("Fear of falling"),
    SYM_114("Fecaluria"),
    SYM_115("Feces in rectum"),
    SYM_116("Feeling hopeless"),
    SYM_117("Feeling strange"),
    SYM_118("Feeling suicidal"),
    SYM_119("Feels hot/feverish"),
    SYM_120("Fever"),
    SYM_121("Flare"),
    SYM_122("Flatulence"),
    SYM_123("Floppy"),
    SYM_124("Flushing"),
    SYM_125("Focal seizures"),
    SYM_126("Food intolerance"),
    SYM_127("Formication"),
    SYM_128("Frail"),
    SYM_129("Fremitus"),
    SYM_130("Frothy sputum"),
    SYM_131("Gag"),
    SYM_132("Gasping for breath"),
    SYM_133("General discomfort"),
    SYM_134("General unsteadiness"),
    SYM_135("Giddy mood"),
    SYM_136("Gravida 0"),
    SYM_137("Gravida 10"),
    SYM_138("Green sputum"),
    SYM_139("Groggy"),
    SYM_140("Guaiac positive"),
    SYM_141("Gurgle"),
    SYM_142("Hacking cough"),
    SYM_143("Haemoptysis"),
    SYM_144("Haemorrhage"),
    SYM_145("Hallucinations auditory"),
    SYM_146("Hallucinations visual"),
    SYM_147("Has religious belief"),
    SYM_148("Headache"),
    SYM_149("Heartburn"),
    SYM_150("Heavy feeling"),
    SYM_151("Heavy legs"),
    SYM_152("Heberden's Node"),
    SYM_153("Hematochezia"),
    SYM_154("Hematocrit decreased"),
    SYM_155("Hematuria"),
    SYM_156("Heme positive"),
    SYM_157("Hemianopsia Homonymous"),
    SYM_158("Hemiplegia"),
    SYM_159("Hemodynamically stable"),
    SYM_160("Hepatomegaly"),
    SYM_161("Hepatosplenomegaly"),
    SYM_162("Hirsutism"),
    SYM_163("History of - blackout"),
    SYM_164("Hoard"),
    SYM_165("Hoarseness"),
    SYM_166("Homelessness"),
    SYM_167("Homicidal thoughts"),
    SYM_168("Hot flush"),
    SYM_169("Hunger"),
    SYM_170("Hydropneumothorax"),
    SYM_171("Hyperacusis"),
    SYM_172("Hypercapnia"),
    SYM_173("Hyperemesis"),
    SYM_174("Hyperhidrosis disorder"),
    SYM_175("Hyperkalemia"),
    SYM_176("Hypersomnia"),
    SYM_177("Hypersomnolence"),
    SYM_178("Hypertonicity"),
    SYM_179("Hyperventilation"),
    SYM_180("Hypesthesia"),
    SYM_181("Hypoalbuminemia"),
    SYM_182("Hypocalcemia result"),
    SYM_183("Hypokalemia"),
    SYM_184("Hypokinesia"),
    SYM_185("Hypometabolism"),
    SYM_186("Hyponatremia"),
    SYM_187("Hypoproteinemia"),
    SYM_188("Hypotension"),
    SYM_189("Hypothermia"),
    SYM_190("Hypotonic"),
    SYM_191("Hypoxemia"),
    SYM_192("Immobile"),
    SYM_193("Impaired cognition"),
    SYM_194("Inappropriate affect"),
    SYM_195("Incoherent"),
    SYM_196("Indifferent mood"),
    SYM_197("Intermenstrual heavy bleeding"),
    SYM_198("Intoxication"),
    SYM_199("Irritable mood"),
    SYM_200("Jugular venous distention"),
    SYM_201("Labored breathing"),
    SYM_202("Lameness"),
    SYM_203("Large-for-dates fetus"),
    SYM_204("Left Atrial Hypertrophy"),
    SYM_205("Lesion"),
    SYM_206("Lethargy"),
    SYM_207("Lightheadedness"),
    SYM_208("Lip smacking"),
    SYM_209("Loose associations"),
    SYM_210("Loss of taste or smell"),
    SYM_211("Low back pain"),
    SYM_212("Lung nodule"),
    SYM_213("Macerated skin"),
    SYM_214("Macule"),
    SYM_215("Malaise"),
    SYM_216("Mass in breast"),
    SYM_217("Mass of body structure"),
    SYM_218("Mediastinal shift"),
    SYM_219("Mental status changes"),
    SYM_220("Metastatic lesion"),
    SYM_221("Milky"),
    SYM_222("Moan"),
    SYM_223("Monoclonal"),
    SYM_224("Monocytosis"),
    SYM_225("Mood depressed"),
    SYM_226("Moody"),
    SYM_227("Motor retardation"),
    SYM_228("Murphy's sign"),
    SYM_229("Muscle hypotonia"),
    SYM_230("Muscle twitch"),
    SYM_231("Myalgia"),
    SYM_232("Mydriasis"),
    SYM_233("Myoclonus"),
    SYM_234("Nasal discharge present"),
    SYM_235("Nasal flaring"),
    SYM_236("Nausea"),
    SYM_237("Nausea and vomiting"),
    SYM_238("Neck stiffness"),
    SYM_239("Neologism"),
    SYM_240("Nervousness"),
    SYM_241("Night sweat"),
    SYM_242("Nightmare"),
    SYM_243("No known drug allergies"),
    SYM_244("No status change"),
    SYM_245("Noisy respiration"),
    SYM_246("Non-productive cough"),
    SYM_247("Nonsmoker"),
    SYM_248("Numbness"),
    SYM_249("Numbness of hand"),
    SYM_250("Oliguria"),
    SYM_251("Orthopnea"),
    SYM_252("Orthostasis"),
    SYM_253("Out of breath"),
    SYM_254("Overweight"),
    SYM_255("Pain"),
    SYM_256("Pain abdominal"),
    SYM_257("Pain back"),
    SYM_258("Pain chest"),
    SYM_259("Pain foot"),
    SYM_260("Pain in lower limb"),
    SYM_261("Pain neck"),
    SYM_262("Painful swallowing"),
    SYM_263("Pallor"),
    SYM_264("Palpitation"),
    SYM_265("Panic"),
    SYM_266("Pansystolic murmur"),
    SYM_267("Paralyse"),
    SYM_268("Paraparesis"),
    SYM_269("Paresis"),
    SYM_270("Paresthesia"),
    SYM_271("Passed stones"),
    SYM_272("Patient non compliance"),
    SYM_273("Pericardial friction rub"),
    SYM_274("Phonophobia"),
    SYM_275("Photophobia"),
    SYM_276("Photopsia"),
    SYM_277("Pin-point pupils"),
    SYM_278("Pleuritic pain"),
    SYM_279("Pneumatouria"),
    SYM_280("Polydypsia"),
    SYM_281("Polymyalgia"),
    SYM_282("Polyuria"),
    SYM_283("Poor dentition"),
    SYM_284("Poor feeding"),
    SYM_285("Posterior Rhinorrhea"),
    SYM_286("Posturing"),
    SYM_287("Presence of q wave"),
    SYM_288("Pressure chest"),
    SYM_289("Previous pregnancies 2"),
    SYM_290("Primigravida"),
    SYM_291("Prodrome"),
    SYM_292("Productive cough"),
    SYM_293("Projectile vomiting"),
    SYM_294("Prostate tender"),
    SYM_295("Prostatism"),
    SYM_296("Proteinemia"),
    SYM_297("Pruritus"),
    SYM_298("Pulse absent"),
    SYM_299("Pulsus Paradoxus"),
    SYM_300("Pustule"),
    SYM_301("Qt interval prolonged"),
    SYM_302("R wave feature"),
    SYM_303("Rale"),
    SYM_304("Rambling speech"),
    SYM_305("Rapid shallow breathing"),
    SYM_306("Red blotches"),
    SYM_307("Redness"),
    SYM_308("Regurgitates after swallowing"),
    SYM_309("Renal angle tenderness"),
    SYM_310("Rest pain"),
    SYM_311("Retch"),
    SYM_312("Retropulsion"),
    SYM_313("Rhd Positive"),
    SYM_314("Rhonchus"),
    SYM_315("Rigor - temperature-associated observation"),
    SYM_316("Rolling of eyes"),
    SYM_317("Room spinning"),
    SYM_318("Satiety early"),
    SYM_319("Scar tissue"),
    SYM_320("Sciatica"),
    SYM_("Scleral icterus"),
    SYM_("Scratch marks"),
    SYM_("Sedentary"),
    SYM_("Seizure"),
    SYM_("Sensory discomfort"),
    SYM_("Shooting pain"),
    SYM_("Shortness of breath"),
    SYM_("Side pain"),
    SYM_("Sinus rhythm"),
    SYM_("Sleeplessness"),
    SYM_("Sleepy"),
    SYM_("Slowing of urinary stream"),
    SYM_("Sneeze"),
    SYM_("Sniffle"),
    SYM_("Snore"),
    SYM_("Snuffle"),
    SYM_("Soft tissue swelling"),
    SYM_("Sore to touch"),
    SYM_("Spasm"),
    SYM_("Speech slurred"),
    SYM_("Splenomegaly"),
    SYM_("Spontaneous rupture of membranes"),
    SYM_("Sputum purulent"),
    SYM_("St segment depression"),
    SYM_("St segment elevation"),
    SYM_("Stahli's line"),
    SYM_("Stiffness"),
    SYM_("Stinging sensation"),
    SYM_("Stool color yellow"),
    SYM_("Stridor"),
    SYM_("Stuffy nose"),
    SYM_("Stupor"),
    SYM_("Suicidal"),
    SYM_("Superimposition"),
    SYM_("Sweat"),
    SYM_("Sweating increased"),
    SYM_("Swelling"),
    SYM_("Symptom aggravating factors"),
    SYM_("Syncope"),
    SYM_("Systolic ejection murmur"),
    SYM_("Systolic murmur"),
    SYM_("T wave inverted"),
    SYM_("Tachypnea"),
    SYM_("Tenesmus"),
    SYM_("Terrify"),
    SYM_("Thicken"),
    SYM_("Throat sore"),
    SYM_("Throbbing sensation quality"),
    SYM_("Tinnitus"),
    SYM_("Titubation"),
    SYM_("Todd paralysis"),
    SYM_("Tonic seizures"),
    SYM_("Transaminitis"),
    SYM_("Transsexual"),
    SYM_("Tremor"),
    SYM_("Tremor resting"),
    SYM_("Tumor cell invasion"),
    SYM_("Unable to concentrate"),
    SYM_("Unconscious state"),
    SYM_("Uncoordination"),
    SYM_("Underweight"),
    SYM_("Unhappy"),
    SYM_("Unresponsiveness"),
    SYM_("Unsteady gait"),
    SYM_("Unwell"),
    SYM_("Urge incontinence"),
    SYM_("Urgency of micturition"),
    SYM_("Urinary hesitation"),
    SYM_("Urinoma"),
    SYM_("Verbal auditory hallucinations"),
    SYM_("Verbally abusive behavior"),
    SYM_("Vertigo"),
    SYM_("Vision blurred"),
    SYM_("Vomiting"),
    SYM_("Weepiness"),
    SYM_("Weight gain"),
    SYM_("Welt"),
    SYM_("Wheelchair bound"),
    SYM_("Wheezing"),
    SYM_("Withdraw"),
    SYM_("Worry"),
    SYM_("Yellow sputum"),

    private String text;

    Symptoms(String text) {
        this.text = text;
    }

    public String getText() {
        return this.text;
    }

    public static Symptoms fromString(String text) {
        for (Symptoms s : Symptoms.values()) {
            if (s.text.equalsIgnoreCase(text)) {
                return s;
            }
        }
        return null;
    }
}
